# vim: set ft=ansible
---
- name: Create Stackrox demo app namespaces
  kubernetes.core.k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  loop: "{{ ocp4_workload_stackrox_demo_apps_namespaces }}"