---
#- name: Demo app namespaces and pull secrets
#  include_tasks: image_pull_secret.yml

- name: Violation policies
  include_tasks: violation_policies.yml

- name: Demo application deployments
  include_tasks: deploy_demos.yml

- name: Network anomalies
  include_tasks: network_anomalies.yml

- name: Baseline processes
  include_tasks: baseline_processes.yml

- name: Add OpenShift policy exceptions
  include_tasks: openshift_policy_fix.yml

- name: CENTRAL ADMIN URL and PASSWORD 
  debug:
    msg: 
      - "CENTRAL URL: https://{{ f_stackrox_central_addr }}"
      - "ADMIN PASSWORD: {{ f_stackrox_admin_password}}"