# vim: set ft=ansible
---
- name: Create API token
  uri:
    url: "https://{{ f_stackrox_central_addr }}/v1/apitokens/generate"
    body: '{"name":"pipelines-ci-token","role":null,"roles":["Continuous Integration"]}'
    method: POST
    user: admin
    password: "{{ f_stackrox_admin_password }}"
    body_format: json
    force_basic_auth: true
    validate_certs: no
  register: r_ci_token_json

- name: Get API token from response
  set_fact:
    f_rox_api_token: "{{ r_ci_token_json.json.token }}"

- name: Create namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ ocp4_workload_stackrox_demo_pipeline_namespace }}"
    state: present

- name: Create secrets for pipelines
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      stringData:
        rox_central_endpoint: "{{ f_stackrox_central_addr }}:443"
        rox_api_token: "{{ f_rox_api_token }}"
      kind: Secret
      metadata:
        name: roxsecrets
        namespace: "{{ ocp4_workload_stackrox_demo_pipeline_namespace }}"
      type: Opaque

- name: Install Operators
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/config/' + item)}}"
  loop:
    - 1-pipeline_subscription.yml.j2

- name: Wait until Pipelines Pods are ready
  k8s_info:
    api_version: v1
    kind: Deployment
    namespace: openshift-pipelines
    name: tekton-pipelines-controller
  register: r_pipeline_controller_deployment
  retries: 120
  delay: 20
  until:
  - r_pipeline_controller_deployment.resources | length | int > 0
  - r_pipeline_controller_deployment.resources[0].status.readyReplicas is defined
  - r_pipeline_controller_deployment.resources[0].status.readyReplicas | int == r_pipeline_controller_deployment.resources[0].spec.replicas | int

- name: Create tasks & pipeline
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/config/' + item)}}"
  loop:
    - 2-rox-deployment-check-task.yml.j2
    - 2-rox-image-check-task.yml.j2
    - 2-rox-image-scan-task.yml.j2
    - 3-rox-deploy-pipeline.yml.j2
    - 3-rox-pipeline.yml.j2

- name: Wait for Rox ClusterTasks to be available
  kubernetes.core.k8s_info:
    kind: ClusterTask
    api_version: tekton.dev/v1beta1
    name: "{{ item }}"
  retries: 120
  delay: 30
  register: r_task_available
  until: r_task_available.resources | length > 0
  loop:
    - "rox-image-scan"
    - "rox-image-check"

- name: Run pipeline against sample images
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/run/4-rox-pipelinerun.yml.j2' ) }}"
  loop:
    - name: "sample-image-old"
      image: "quay.io/rhacs-demo/sample-image:getting-started-old"
    - name: "sample-image-new"
      image: "quay.io/rhacs-demo/sample-image:getting-started"

- name: Run pipeline against deployment yamls
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/run/4-rox-deploy-pipelinerun.yml.j2' ) }}"
  loop: "{{ ocp4_workload_stackrox_demo_pipeline_deployment_yamls }}"

- name: CENTRAL ADMIN URL and PASSWORD 
  debug:
    msg: 
      - "CENTRAL URL: https://{{ f_stackrox_central_addr }}"
      - "ADMIN PASSWORD: {{ f_stackrox_admin_password}}"