---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: Group
    name: admins
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-accounts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: frontend
  - kind: ServiceAccount
    name: default
    namespace: backend
  - kind: ServiceAccount
    name: backend-atlas
    namespace: backend
  - kind: ServiceAccount
    name: default
    namespace: medical
  - kind: ServiceAccount
    name: default
    namespace: operations
  - kind: ServiceAccount
    name: puppet-master
    namespace: operations
  - kind: ServiceAccount
    name: default
    namespace: "payments"
  - kind: ServiceAccount
    name: mastercard-processor
    namespace: "payments"
  - kind: ServiceAccount
    name: visa-processor
    namespace: "payments"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:basic-user
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: system:unauthenticated
    apiGroup: rbac.authorization.k8s.io